export const application = {
    SHOW: 'APPLICATION_SHOW',
    HEIGHT: 'APPLICATION_HEIGHT',
    WIDTH: 'APPLICATION_WIDTH',
};

export const mainMessage = {
    OPEN: 'MAIN_MESSAGE_OPEN',
    SEVERITY: 'MAIN_MESSAGE_SEVERITY',
    MESSAGE: 'MAIN_MESSAGE_MESSAGE',
};

export const map = {
    CHANGE_FIELD: 'MAP_CHANGE_FIELD',
    SET_FIELD: 'MAP_SET_FIELD',
    REQUEST: 'MAP_REQUEST',
    SAVE: 'MAP_SAVE',
    SET_OBJECT: 'MAP_SET_OBJECT',
    SET_FORM_ERRORS: 'MAP_SET_FORM_ERRORS',
    LOADING: 'MAP_LOADING',
    CHECK_ERRORS: 'MAP_CHECK_ERRORS',
};

export const marker = {
    SET_OBJECT: 'MARKER_SET_OBJECT',
    LOADING: 'MARKER_LOADING',
    CHANGE_STEP: 'MARKER_CHANGE_STEP',
    SET_STEP: 'MARKER_SET_STEP',
    REQUEST_UPDATE: 'MARKER_REQUEST_UPDATE',
    // : 'MARKER_',
};
